name: build-windows-portable
'on':
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        shell: bash
        run: |
          npm config set registry https://registry.npmmirror.com
          export ELECTRON_MIRROR=https://npmmirror.com/mirrors/electron/
          export ELECTRON_BUILDER_BINARIES_MIRROR=https://npmmirror.com/mirrors/electron-builder-binaries/
          npm install --no-audit --no-fund

      - name: Fetch wewe-rss source (Node project)
        shell: bash
        run: |
          mkdir -p resources/wewe-rss
          git clone --depth 1 https://github.com/cooderl/wewe-rss resources/wewe-rss

      - name: Build (electron-builder)
        run: npm run dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dc-daily-desktop_win64_portable
          path: dist/dc-daily-desktop_*_win64_portable.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.0-alpha.${{ github.run_number }}
          name: v0.1.0-alpha.${{ github.run_number }}
          make_latest: false
          draft: false
          prerelease: true
          files: |
            dist/dc-daily-desktop_*_win64_portable.zip
